name: Auto Merge

on:
  push:
    branches:
      - '*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Merge into Master
      run: |
        git checkout Master
        git pull origin Master
        git merge ${{ github.event.ref }}
        git push origin Master
